### ISSUE TITLE
Undefined function class_basename

### ISSUE THREAD

**Issue by Nks** [ianchadwick/dxi#1]
It seems you are using Laravel function `class_basename` in the package and it can call some errors like `Call to undefined function Dxi\\Commands\\Dataset\\Contact\\class_basename() in /vagrant/vendor/ianchadwick/dxi/src/Commands/Dataset/Contact/Create.php on line 65`. 

I'm added this function in my helpers in my project and it's working fine, but it's not best solution I think:
```
if (! function_exists('class_basename')) {
    /**
     * Get the class "basename" of the given object / class.
     *
     * @param  string|object  $class
     * @return string
     */
    function class_basename($class)
    {
        $class = is_object($class) ? get_class($class) : $class;

        return basename(str_replace('\\', '/', $class));
    }
}

```

**Comment by ianchadwick** [comment]
Whoops and good spot on it being Laravel. I decided to keep it simple and just return a string as there really is no need for the extra complication.

Thanks!

**Comment by Nks** [comment]
@ianchadwick thanks for updates 👍
